# Upptime Configuration - External Status Page Failover
# This config monitors publicly accessible services from GitHub Actions
#
# Note: The status page is built with a custom Next.js frontend (see src/)
# Documentation: https://upptime.js.org/docs/

owner: ara1106
repo: upptime

# Disable the default Upptime status page - we use a custom Next.js frontend
status-website:
  cname: status.kero-ara.com

# Only monitor publicly accessible endpoints
# Internal services (.rem.home) are monitored by Gatus
sites:
  # Identity & Portal
  - name: KeroHub Portal
    url: https://kero-ara.com/api/health
    icon: https://kero-ara.com/favicon.ico

  - name: KeroHub Auth
    url: https://kero-ara.com/api/auth/session
    expectedStatusCodes:
      - 200
      - 401  # Unauthorized is expected without session

  # Media Services (Public)
  - name: Jellyfin
    url: https://jellyfin.kero-ara.com/health
    icon: https://jellyfin.kero-ara.com/web/favicon.ico

  - name: Jellyseerr
    url: https://jellyseerr.kero-ara.com/api/v1/status

# Check every 5 minutes via GitHub Actions
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"

# Commits configuration
commitMessages:
  commitMessagePrefix: "[status]"
  statusChangeCommitMessage: "$PREFIX $NAME is $STATUS"
  startCommitMessage: "$PREFIX Starting status monitoring"
  readmeCommitMessage: "$PREFIX Update README"

# I18n - cleaner labels
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident Report
  activeMaintenances: Scheduled Maintenance
  scheduledMaintenances: Upcoming Maintenance
  noMaintenances: No scheduled maintenance
  up: Operational
  down: Down
  degraded: Degraded

# User/org info
user:
  repo: ara1106/remlab-configs
