# Upptime Configuration - External Status Page Failover
# This config monitors publicly accessible services from GitHub Actions
#
# Documentation: https://upptime.js.org/docs/

owner: ara1106
repo: upptime

# Status page configuration
status-website:
  cname: status.kero-ara.com
  baseUrl: /
  name: RemLab Status
  logoUrl: https://kero-ara.com/logo.png
  theme: dark

  # Clean intro with gradient text effect
  introTitle: "**RemLab** Status"
  introMessage: |
    External monitoring for public-facing services.
    For detailed internal status, visit [KeroHub](https://kero-ara.com/status).

  # Navigation links
  navbar:
    - title: KeroHub
      href: https://kero-ara.com
    - title: Jellyfin
      href: https://jellyfin.kero-ara.com
    - title: Request Media
      href: https://jellyseerr.kero-ara.com

  # Custom CSS targeting Upptime's actual Svelte components
  css: |
    /* ===== Theme Variables ===== */
    :root {
      --body-background-color: #0a0c10;
      --body-text-color: #e6edf3;
      --card-background-color: #151921;
      --card-border-color: #30363d;
      --nav-background-color: #010409;
      --link-color: #58a6ff;
      --success-color: #3fb950;
      --warning-color: #d29922;
      --danger-color: #f85149;
    }

    /* ===== Base Styles ===== */
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(180deg, #0a0c10 0%, #0d1117 100%);
      min-height: 100vh;
    }

    /* ===== Navigation ===== */
    nav {
      background: rgba(1, 4, 9, 0.8) !important;
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      border-bottom: 1px solid #21262d !important;
      padding: 0.75rem 0;
    }

    nav .container {
      max-width: 1200px;
    }

    nav .logo {
      font-weight: 600;
      font-size: 1.1rem;
    }

    nav .logo img {
      height: 32px;
      width: auto;
      border-radius: 6px;
    }

    nav ul a {
      padding: 0.5rem 1rem;
      border-radius: 6px;
      transition: all 0.15s ease;
      color: #8b949e;
    }

    nav ul a:hover {
      background: #21262d;
      color: #e6edf3;
    }

    /* ===== Header / Intro ===== */
    header {
      text-align: center;
      padding: 3rem 1rem 2rem;
    }

    header h1 {
      font-size: 2.75rem;
      font-weight: 800;
      letter-spacing: -0.02em;
      background: linear-gradient(135deg, #58a6ff 0%, #a371f7 50%, #f778ba 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      margin-bottom: 0.75rem;
    }

    header h1 strong {
      font-weight: 800;
    }

    header p, header .lead {
      color: #8b949e;
      font-size: 1.1rem;
      max-width: 500px;
      margin: 0 auto;
    }

    header a {
      color: #58a6ff;
      text-decoration: none;
      border-bottom: 1px solid transparent;
      transition: border-color 0.15s ease;
    }

    header a:hover {
      border-bottom-color: #58a6ff;
    }

    /* ===== Status Summary (All systems operational) ===== */
    section > div[class*="status"] {
      background: linear-gradient(135deg, #238636 0%, #2ea043 100%);
      border-radius: 12px;
      padding: 1rem 1.5rem;
      margin: 1.5rem 0;
      box-shadow: 0 4px 20px rgba(46, 160, 67, 0.2);
    }

    /* ===== Live Status Section ===== */
    .live-status, section[class*="live"] {
      margin-top: 2rem;
    }

    h2 {
      font-size: 1.5rem;
      font-weight: 600;
      color: #e6edf3;
      margin-bottom: 1rem;
    }

    /* Time range selector */
    form[class*="svelte"] {
      display: flex;
      gap: 0.25rem;
      background: #21262d;
      padding: 4px;
      border-radius: 8px;
      width: fit-content;
    }

    form label {
      padding: 0.4rem 0.8rem;
      border-radius: 6px;
      cursor: pointer;
      transition: all 0.15s ease;
      color: #8b949e;
      font-size: 0.9rem;
    }

    form input:checked + label {
      background: #30363d;
      color: #e6edf3;
    }

    form label:hover {
      color: #e6edf3;
    }

    /* ===== Service Cards ===== */
    section article, .live-status > div > div {
      background: #151921;
      border: 1px solid #21262d;
      border-radius: 12px;
      padding: 1.25rem;
      margin-bottom: 1rem;
      transition: all 0.2s ease;
    }

    section article:hover, .live-status > div > div:hover {
      border-color: #30363d;
      box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3);
      transform: translateY(-1px);
    }

    /* Service name links */
    section article a, .live-status a {
      color: #58a6ff;
      font-weight: 600;
      font-size: 1.1rem;
      text-decoration: none;
    }

    section article a:hover, .live-status a:hover {
      text-decoration: underline;
    }

    /* Uptime stats */
    section article p, .live-status p {
      color: #8b949e;
      margin: 0.25rem 0;
      font-size: 0.95rem;
    }

    /* ===== Status Indicator Icons ===== */
    [class*="up"], [class*="success"] {
      color: #3fb950;
    }

    [class*="down"], [class*="error"] {
      color: #f85149;
    }

    /* ===== Response Time Graphs ===== */
    canvas, .chart, img[src*="graph"] {
      border-radius: 8px;
      filter: saturate(1.2);
    }

    /* ===== Footer ===== */
    footer {
      text-align: center;
      padding: 3rem 1rem;
      color: #484f58;
      font-size: 0.9rem;
      border-top: 1px solid #21262d;
      margin-top: 3rem;
    }

    footer a {
      color: #58a6ff;
    }

    /* ===== Loading Spinners ===== */
    .loading svg {
      opacity: 0.5;
    }

    /* ===== Mobile Responsive ===== */
    @media (max-width: 768px) {
      header h1 {
        font-size: 2rem;
      }

      header p {
        font-size: 1rem;
        padding: 0 1rem;
      }

      nav ul {
        gap: 0.25rem;
      }

      nav ul a {
        padding: 0.4rem 0.6rem;
        font-size: 0.9rem;
      }

      form[class*="svelte"] {
        flex-wrap: wrap;
      }
    }

    /* ===== Smooth Transitions ===== */
    *, *::before, *::after {
      transition-property: background-color, border-color, color, box-shadow, transform;
      transition-duration: 0.15s;
      transition-timing-function: ease;
    }

    /* ===== Scrollbar Styling ===== */
    ::-webkit-scrollbar {
      width: 8px;
      height: 8px;
    }

    ::-webkit-scrollbar-track {
      background: #0d1117;
    }

    ::-webkit-scrollbar-thumb {
      background: #30363d;
      border-radius: 4px;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #484f58;
    }

# Only monitor publicly accessible endpoints
# Internal services (.rem.home) are monitored by Gatus
sites:
  # Identity & Portal
  - name: KeroHub Portal
    url: https://kero-ara.com/api/health
    icon: https://kero-ara.com/favicon.ico

  - name: KeroHub Auth
    url: https://kero-ara.com/api/auth/session
    expectedStatusCodes:
      - 200
      - 401  # Unauthorized is expected without session

  # Media Services (Public)
  - name: Jellyfin
    url: https://jellyfin.kero-ara.com/health
    icon: https://jellyfin.kero-ara.com/web/favicon.ico

  - name: Jellyseerr
    url: https://jellyseerr.kero-ara.com/api/v1/status

# Check every 5 minutes via GitHub Actions
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"

# Commits configuration
commitMessages:
  commitMessagePrefix: "[status]"
  statusChangeCommitMessage: "$PREFIX $NAME is $STATUS"
  startCommitMessage: "$PREFIX Starting status monitoring"
  readmeCommitMessage: "$PREFIX Update README"

# I18n - cleaner labels
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident Report
  activeMaintenances: Scheduled Maintenance
  scheduledMaintenances: Upcoming Maintenance
  noMaintenances: No scheduled maintenance
  up: Operational
  down: Down
  degraded: Degraded

# User/org info
user:
  repo: ara1106/remlab-configs
